#![allow(dead_code)]

use anyhow::Result;

use crate::arch;

pub fn exec_syscall(idx: usize) -> Result<usize> {
    match idx {
        // 0 => arch::x86::x86_64::syscalls::handlers::read::syscall_read(0),
        1 => arch::x86::x86_64::syscalls::handlers::write::syscall_write(1),
        // 2 => arch::x86::x86_64::syscalls::handlers::open::syscall_open(2),
        // 3 => arch::x86::x86_64::syscalls::handlers::close::syscall_close(3),
        // 4 => arch::x86::x86_64::syscalls::handlers::stat::syscall_stat(4),
        // 5 => arch::x86::x86_64::syscalls::handlers::fstat::syscall_fstat(5),
        // 6 => arch::x86::x86_64::syscalls::handlers::lstat::syscall_lstat(6),
        // 7 => arch::x86::x86_64::syscalls::handlers::poll::syscall_poll(7),
        // 8 => arch::x86::x86_64::syscalls::handlers::lseek::syscall_lseek(8),
        // 9 => arch::x86::x86_64::syscalls::handlers::mmap::syscall_mmap(9),
        // 10 => arch::x86::x86_64::syscalls::handlers::mprotect::syscall_mprotect(10),
        // 11 => arch::x86::x86_64::syscalls::handlers::munmap::syscall_munmap(11),
        // 12 => arch::x86::x86_64::syscalls::handlers::brk::syscall_brk(12),
        // 13 => arch::x86::x86_64::syscalls::handlers::rt_sigaction::syscall_rt_sigaction(13),
        // 14 => arch::x86::x86_64::syscalls::handlers::rt_sigprocmask::syscall_rt_sigprocmask(14),
        // 15 => arch::x86::x86_64::syscalls::handlers::rt_sigreturn::syscall_rt_sigreturn(15),
        // 16 => arch::x86::x86_64::syscalls::handlers::ioctl::syscall_ioctl(16),
        // 17 => arch::x86::x86_64::syscalls::handlers::pread64::syscall_pread64(17),
        // 18 => arch::x86::x86_64::syscalls::handlers::pwrite64::syscall_pwrite64(18),
        // 19 => arch::x86::x86_64::syscalls::handlers::readv::syscall_readv(19),
        // 20 => arch::x86::x86_64::syscalls::handlers::writev::syscall_writev(20),
        // 21 => arch::x86::x86_64::syscalls::handlers::access::syscall_access(21),
        // 22 => arch::x86::x86_64::syscalls::handlers::pipe::syscall_pipe(22),
        // 23 => arch::x86::x86_64::syscalls::handlers::select::syscall_select(23),
        // 24 => arch::x86::x86_64::syscalls::handlers::sched_yield::syscall_sched_yield(24),
        // 25 => arch::x86::x86_64::syscalls::handlers::mremap::syscall_mremap(25),
        // 26 => arch::x86::x86_64::syscalls::handlers::msync::syscall_msync(26),
        // 27 => arch::x86::x86_64::syscalls::handlers::mincore::syscall_mincore(27),
        // 28 => arch::x86::x86_64::syscalls::handlers::madvise::syscall_madvise(28),
        // 29 => arch::x86::x86_64::syscalls::handlers::shmget::syscall_shmget(29),
        // 30 => arch::x86::x86_64::syscalls::handlers::shmat::syscall_shmat(30),
        // 31 => arch::x86::x86_64::syscalls::handlers::shmctl::syscall_shmctl(31),
        // 32 => arch::x86::x86_64::syscalls::handlers::dup::syscall_dup(32),
        // 33 => arch::x86::x86_64::syscalls::handlers::dup2::syscall_dup2(33),
        // 34 => arch::x86::x86_64::syscalls::handlers::pause::syscall_pause(34),
        // 35 => arch::x86::x86_64::syscalls::handlers::nanosleep::syscall_nanosleep(35),
        // 36 => arch::x86::x86_64::syscalls::handlers::getitimer::syscall_getitimer(36),
        // 37 => arch::x86::x86_64::syscalls::handlers::alarm::syscall_alarm(37),
        // 38 => arch::x86::x86_64::syscalls::handlers::setitimer::syscall_setitimer(38),
        // 39 => arch::x86::x86_64::syscalls::handlers::getpid::syscall_getpid(39),
        // 40 => arch::x86::x86_64::syscalls::handlers::sendfile::syscall_sendfile(40),
        // 41 => arch::x86::x86_64::syscalls::handlers::socket::syscall_socket(41),
        // 42 => arch::x86::x86_64::syscalls::handlers::connect::syscall_connect(42),
        // 43 => arch::x86::x86_64::syscalls::handlers::accept::syscall_accept(43),
        // 44 => arch::x86::x86_64::syscalls::handlers::sendto::syscall_sendto(44),
        // 45 => arch::x86::x86_64::syscalls::handlers::recvfrom::syscall_recvfrom(45),
        // 46 => arch::x86::x86_64::syscalls::handlers::sendmsg::syscall_sendmsg(46),
        // 47 => arch::x86::x86_64::syscalls::handlers::recvmsg::syscall_recvmsg(47),
        // 48 => arch::x86::x86_64::syscalls::handlers::shutdown::syscall_shutdown(48),
        // 49 => arch::x86::x86_64::syscalls::handlers::bind::syscall_bind(49),
        // 50 => arch::x86::x86_64::syscalls::handlers::listen::syscall_listen(50),
        // 51 => arch::x86::x86_64::syscalls::handlers::getsockname::syscall_getsockname(51),
        // 52 => arch::x86::x86_64::syscalls::handlers::getpeername::syscall_getpeername(52),
        // 53 => arch::x86::x86_64::syscalls::handlers::socketpair::syscall_socketpair(53),
        // 54 => arch::x86::x86_64::syscalls::handlers::setsockopt::syscall_setsockopt(54),
        // 55 => arch::x86::x86_64::syscalls::handlers::getsockopt::syscall_getsockopt(55),
        // 56 => arch::x86::x86_64::syscalls::handlers::clone::syscall_clone(56),
        // 57 => arch::x86::x86_64::syscalls::handlers::fork::syscall_fork(57),
        // 58 => arch::x86::x86_64::syscalls::handlers::vfork::syscall_vfork(58),
        // 59 => arch::x86::x86_64::syscalls::handlers::execve::syscall_execve(59),
        60 => arch::x86::x86_64::syscalls::handlers::exit::syscall_exit(60),
        // 61 => arch::x86::x86_64::syscalls::handlers::wait4::syscall_wait4(61),
        // 62 => arch::x86::x86_64::syscalls::handlers::kill::syscall_kill(62),
        // 63 => arch::x86::x86_64::syscalls::handlers::uname::syscall_uname(63),
        // 64 => arch::x86::x86_64::syscalls::handlers::semget::syscall_semget(64),
        // 65 => arch::x86::x86_64::syscalls::handlers::semop::syscall_semop(65),
        // 66 => arch::x86::x86_64::syscalls::handlers::semctl::syscall_semctl(66),
        // 67 => arch::x86::x86_64::syscalls::handlers::shmdt::syscall_shmdt(67),
        // 68 => arch::x86::x86_64::syscalls::handlers::msgget::syscall_msgget(68),
        // 69 => arch::x86::x86_64::syscalls::handlers::msgsnd::syscall_msgsnd(69),
        // 70 => arch::x86::x86_64::syscalls::handlers::msgrcv::syscall_msgrcv(70),
        // 71 => arch::x86::x86_64::syscalls::handlers::msgctl::syscall_msgctl(71),
        // 72 => arch::x86::x86_64::syscalls::handlers::fcntl::syscall_fcntl(72),
        // 73 => arch::x86::x86_64::syscalls::handlers::flock::syscall_flock(73),
        // 74 => arch::x86::x86_64::syscalls::handlers::fsync::syscall_fsync(74),
        // 75 => arch::x86::x86_64::syscalls::handlers::fdatasync::syscall_fdatasync(75),
        // 76 => arch::x86::x86_64::syscalls::handlers::truncate::syscall_truncate(76),
        // 77 => arch::x86::x86_64::syscalls::handlers::ftruncate::syscall_ftruncate(77),
        // 78 => arch::x86::x86_64::syscalls::handlers::getdents::syscall_getdents(78),
        // 79 => arch::x86::x86_64::syscalls::handlers::getcwd::syscall_getcwd(79),
        // 80 => arch::x86::x86_64::syscalls::handlers::chdir::syscall_chdir(80),
        // 81 => arch::x86::x86_64::syscalls::handlers::fchdir::syscall_fchdir(81),
        // 82 => arch::x86::x86_64::syscalls::handlers::rename::syscall_rename(82),
        // 83 => arch::x86::x86_64::syscalls::handlers::mkdir::syscall_mkdir(83),
        // 84 => arch::x86::x86_64::syscalls::handlers::rmdir::syscall_rmdir(84),
        // 85 => arch::x86::x86_64::syscalls::handlers::creat::syscall_creat(85),
        // 86 => arch::x86::x86_64::syscalls::handlers::link::syscall_link(86),
        // 87 => arch::x86::x86_64::syscalls::handlers::unlink::syscall_unlink(87),
        // 88 => arch::x86::x86_64::syscalls::handlers::symlink::syscall_symlink(88),
        // 89 => arch::x86::x86_64::syscalls::handlers::readlink::syscall_readlink(89),
        // 90 => arch::x86::x86_64::syscalls::handlers::chmod::syscall_chmod(90),
        // 91 => arch::x86::x86_64::syscalls::handlers::fchmod::syscall_fchmod(91),
        // 92 => arch::x86::x86_64::syscalls::handlers::chown::syscall_chown(92),
        // 93 => arch::x86::x86_64::syscalls::handlers::fchown::syscall_fchown(93),
        // 94 => arch::x86::x86_64::syscalls::handlers::lchown::syscall_lchown(94),
        // 95 => arch::x86::x86_64::syscalls::handlers::umask::syscall_umask(95),
        // 96 => arch::x86::x86_64::syscalls::handlers::gettimeofday::syscall_gettimeofday(96),
        // 97 => arch::x86::x86_64::syscalls::handlers::getrlimit::syscall_getrlimit(97),
        // 98 => arch::x86::x86_64::syscalls::handlers::getrusage::syscall_getrusage(98),
        // 99 => arch::x86::x86_64::syscalls::handlers::sysinfo::syscall_sysinfo(99),
        // 100 => arch::x86::x86_64::syscalls::handlers::times::syscall_times(100),
        // 101 => arch::x86::x86_64::syscalls::handlers::ptrace::syscall_ptrace(101),
        // 102 => arch::x86::x86_64::syscalls::handlers::getuid::syscall_getuid(102),
        // 103 => arch::x86::x86_64::syscalls::handlers::syslog::syscall_syslog(103),
        // 104 => arch::x86::x86_64::syscalls::handlers::getgid::syscall_getgid(104),
        // 105 => arch::x86::x86_64::syscalls::handlers::setuid::syscall_setuid(105),
        // 106 => arch::x86::x86_64::syscalls::handlers::setgid::syscall_setgid(106),
        // 107 => arch::x86::x86_64::syscalls::handlers::geteuid::syscall_geteuid(107),
        // 108 => arch::x86::x86_64::syscalls::handlers::getegid::syscall_getegid(108),
        // 109 => arch::x86::x86_64::syscalls::handlers::setpgid::syscall_setpgid(109),
        // 110 => arch::x86::x86_64::syscalls::handlers::getppid::syscall_getppid(110),
        // 111 => arch::x86::x86_64::syscalls::handlers::getpgrp::syscall_getpgrp(111),
        // 112 => arch::x86::x86_64::syscalls::handlers::setsid::syscall_setsid(112),
        // 113 => arch::x86::x86_64::syscalls::handlers::setreuid::syscall_setreuid(113),
        // 114 => arch::x86::x86_64::syscalls::handlers::setregid::syscall_setregid(114),
        // 115 => arch::x86::x86_64::syscalls::handlers::getgroups::syscall_getgroups(115),
        // 116 => arch::x86::x86_64::syscalls::handlers::setgroups::syscall_setgroups(116),
        // 117 => arch::x86::x86_64::syscalls::handlers::setresuid::syscall_setresuid(117),
        // 118 => arch::x86::x86_64::syscalls::handlers::getresuid::syscall_getresuid(118),
        // 119 => arch::x86::x86_64::syscalls::handlers::setresgid::syscall_setresgid(119),
        // 120 => arch::x86::x86_64::syscalls::handlers::getresgid::syscall_getresgid(120),
        // 121 => arch::x86::x86_64::syscalls::handlers::getpgid::syscall_getpgid(121),
        // 122 => arch::x86::x86_64::syscalls::handlers::setfsuid::syscall_setfsuid(122),
        // 123 => arch::x86::x86_64::syscalls::handlers::setfsgid::syscall_setfsgid(123),
        // 124 => arch::x86::x86_64::syscalls::handlers::getsid::syscall_getsid(124),
        // 125 => arch::x86::x86_64::syscalls::handlers::capget::syscall_capget(125),
        // 126 => arch::x86::x86_64::syscalls::handlers::capset::syscall_capset(126),
        // 127 => arch::x86::x86_64::syscalls::handlers::rt_sigpending::syscall_rt_sigpending(127),
        // 128 => arch::x86::x86_64::syscalls::handlers::rt_sigtimedwait::syscall_rt_sigtimedwait(128),
        // 129 => arch::x86::x86_64::syscalls::handlers::rt_sigqueueinfo::syscall_rt_sigqueueinfo(129),
        // 130 => arch::x86::x86_64::syscalls::handlers::rt_sigsuspend::syscall_rt_sigsuspend(130),
        // 131 => arch::x86::x86_64::syscalls::handlers::sigaltstack::syscall_sigaltstack(131),
        // 132 => arch::x86::x86_64::syscalls::handlers::utime::syscall_utime(132),
        // 133 => arch::x86::x86_64::syscalls::handlers::mknod::syscall_mknod(133),
        // 134 => arch::x86::x86_64::syscalls::handlers::uselib::syscall_uselib(134),
        // 135 => arch::x86::x86_64::syscalls::handlers::personality::syscall_personality(135),
        // 136 => arch::x86::x86_64::syscalls::handlers::ustat::syscall_ustat(136),
        // 137 => arch::x86::x86_64::syscalls::handlers::statfs::syscall_statfs(137),
        // 138 => arch::x86::x86_64::syscalls::handlers::fstatfs::syscall_fstatfs(138),
        // 139 => arch::x86::x86_64::syscalls::handlers::sysfs::syscall_sysfs(139),
        // 140 => arch::x86::x86_64::syscalls::handlers::getpriority::syscall_getpriority(140),
        // 141 => arch::x86::x86_64::syscalls::handlers::setpriority::syscall_setpriority(141),
        // 142 => arch::x86::x86_64::syscalls::handlers::sched_setparam::syscall_sched_setparam(142),
        // 143 => arch::x86::x86_64::syscalls::handlers::sched_getparam::syscall_sched_getparam(143),
        // 144 => arch::x86::x86_64::syscalls::handlers::sched_setscheduler::syscall_sched_setscheduler(144),
        // 145 => arch::x86::x86_64::syscalls::handlers::sched_getscheduler::syscall_sched_getscheduler(145),
        // 146 => arch::x86::x86_64::syscalls::handlers::sched_get_priority_max::syscall_sched_get_priority_max(146),
        // 147 => arch::x86::x86_64::syscalls::handlers::sched_get_priority_min::syscall_sched_get_priority_min(147),
        // 148 => arch::x86::x86_64::syscalls::handlers::sched_rr_get_interval::syscall_sched_rr_get_interval(148),
        // 149 => arch::x86::x86_64::syscalls::handlers::mlock::syscall_mlock(149),
        // 150 => arch::x86::x86_64::syscalls::handlers::munlock::syscall_munlock(150),
        // 151 => arch::x86::x86_64::syscalls::handlers::mlockall::syscall_mlockall(151),
        // 152 => arch::x86::x86_64::syscalls::handlers::munlockall::syscall_munlockall(152),
        // 153 => arch::x86::x86_64::syscalls::handlers::vhangup::syscall_vhangup(153),
        // 154 => arch::x86::x86_64::syscalls::handlers::modify_ldt::syscall_modify_ldt(154),
        // 155 => arch::x86::x86_64::syscalls::handlers::pivot_root::syscall_pivot_root(155),
        // 156 => arch::x86::x86_64::syscalls::handlers::_sysctl::syscall__sysctl(156),
        // 157 => arch::x86::x86_64::syscalls::handlers::prctl::syscall_prctl(157),
        // 158 => arch::x86::x86_64::syscalls::handlers::arch_prctl::syscall_arch_prctl(158),
        // 159 => arch::x86::x86_64::syscalls::handlers::adjtimex::syscall_adjtimex(159),
        // 160 => arch::x86::x86_64::syscalls::handlers::setrlimit::syscall_setrlimit(160),
        // 161 => arch::x86::x86_64::syscalls::handlers::chroot::syscall_chroot(161),
        // 162 => arch::x86::x86_64::syscalls::handlers::sync::syscall_sync(162),
        // 163 => arch::x86::x86_64::syscalls::handlers::acct::syscall_acct(163),
        // 164 => arch::x86::x86_64::syscalls::handlers::settimeofday::syscall_settimeofday(164),
        // 165 => arch::x86::x86_64::syscalls::handlers::mount::syscall_mount(165),
        // 166 => arch::x86::x86_64::syscalls::handlers::umount2::syscall_umount2(166),
        // 167 => arch::x86::x86_64::syscalls::handlers::swapon::syscall_swapon(167),
        // 168 => arch::x86::x86_64::syscalls::handlers::swapoff::syscall_swapoff(168),
        // 169 => arch::x86::x86_64::syscalls::handlers::reboot::syscall_reboot(169),
        // 170 => arch::x86::x86_64::syscalls::handlers::sethostname::syscall_sethostname(170),
        // 171 => arch::x86::x86_64::syscalls::handlers::setdomainname::syscall_setdomainname(171),
        // 172 => arch::x86::x86_64::syscalls::handlers::iopl::syscall_iopl(172),
        // 173 => arch::x86::x86_64::syscalls::handlers::ioperm::syscall_ioperm(173),
        // 174 => arch::x86::x86_64::syscalls::handlers::create_module::syscall_create_module(174),
        // 175 => arch::x86::x86_64::syscalls::handlers::init_module::syscall_init_module(175),
        // 176 => arch::x86::x86_64::syscalls::handlers::delete_module::syscall_delete_module(176),
        // 177 => arch::x86::x86_64::syscalls::handlers::get_kernel_syms::syscall_get_kernel_syms(177),
        // 178 => arch::x86::x86_64::syscalls::handlers::query_module::syscall_query_module(178),
        // 179 => arch::x86::x86_64::syscalls::handlers::quotactl::syscall_quotactl(179),
        // 180 => arch::x86::x86_64::syscalls::handlers::nfsservctl::syscall_nfsservctl(180),
        // 181 => arch::x86::x86_64::syscalls::handlers::getpmsg::syscall_getpmsg(181),
        // 182 => arch::x86::x86_64::syscalls::handlers::putpmsg::syscall_putpmsg(182),
        // 183 => arch::x86::x86_64::syscalls::handlers::afs_syscall::syscall_afs_syscall(183),
        // 184 => arch::x86::x86_64::syscalls::handlers::tuxcall::syscall_tuxcall(184),
        // 185 => arch::x86::x86_64::syscalls::handlers::security::syscall_security(185),
        // 186 => arch::x86::x86_64::syscalls::handlers::gettid::syscall_gettid(186),
        // 187 => arch::x86::x86_64::syscalls::handlers::readahead::syscall_readahead(187),
        // 188 => arch::x86::x86_64::syscalls::handlers::setxattr::syscall_setxattr(188),
        // 189 => arch::x86::x86_64::syscalls::handlers::lsetxattr::syscall_lsetxattr(189),
        // 190 => arch::x86::x86_64::syscalls::handlers::fsetxattr::syscall_fsetxattr(190),
        // 191 => arch::x86::x86_64::syscalls::handlers::getxattr::syscall_getxattr(191),
        // 192 => arch::x86::x86_64::syscalls::handlers::lgetxattr::syscall_lgetxattr(192),
        // 193 => arch::x86::x86_64::syscalls::handlers::fgetxattr::syscall_fgetxattr(193),
        // 194 => arch::x86::x86_64::syscalls::handlers::listxattr::syscall_listxattr(194),
        // 195 => arch::x86::x86_64::syscalls::handlers::llistxattr::syscall_llistxattr(195),
        // 196 => arch::x86::x86_64::syscalls::handlers::flistxattr::syscall_flistxattr(196),
        // 197 => arch::x86::x86_64::syscalls::handlers::removexattr::syscall_removexattr(197),
        // 198 => arch::x86::x86_64::syscalls::handlers::lremovexattr::syscall_lremovexattr(198),
        // 199 => arch::x86::x86_64::syscalls::handlers::fremovexattr::syscall_fremovexattr(199),
        // 200 => arch::x86::x86_64::syscalls::handlers::tkill::syscall_tkill(200),
        // 201 => arch::x86::x86_64::syscalls::handlers::time::syscall_time(201),
        // 202 => arch::x86::x86_64::syscalls::handlers::futex::syscall_futex(202),
        // 203 => arch::x86::x86_64::syscalls::handlers::sched_setaffinity::syscall_sched_setaffinity(203),
        // 204 => arch::x86::x86_64::syscalls::handlers::sched_getaffinity::syscall_sched_getaffinity(204),
        // 205 => arch::x86::x86_64::syscalls::handlers::set_thread_area::syscall_set_thread_area(205),
        // 206 => arch::x86::x86_64::syscalls::handlers::io_setup::syscall_io_setup(206),
        // 207 => arch::x86::x86_64::syscalls::handlers::io_destroy::syscall_io_destroy(207),
        // 208 => arch::x86::x86_64::syscalls::handlers::io_getevents::syscall_io_getevents(208),
        // 209 => arch::x86::x86_64::syscalls::handlers::io_submit::syscall_io_submit(209),
        // 210 => arch::x86::x86_64::syscalls::handlers::io_cancel::syscall_io_cancel(210),
        // 211 => arch::x86::x86_64::syscalls::handlers::get_thread_area::syscall_get_thread_area(211),
        // 212 => arch::x86::x86_64::syscalls::handlers::lookup_dcookie::syscall_lookup_dcookie(212),
        // 213 => arch::x86::x86_64::syscalls::handlers::epoll_create::syscall_epoll_create(213),
        // 214 => arch::x86::x86_64::syscalls::handlers::epoll_ctl_old::syscall_epoll_ctl_old(214),
        // 215 => arch::x86::x86_64::syscalls::handlers::epoll_wait_old::syscall_epoll_wait_old(215),
        // 216 => arch::x86::x86_64::syscalls::handlers::remap_file_pages::syscall_remap_file_pages(216),
        // 217 => arch::x86::x86_64::syscalls::handlers::getdents64::syscall_getdents64(217),
        // 218 => arch::x86::x86_64::syscalls::handlers::set_tid_address::syscall_set_tid_address(218),
        // 219 => arch::x86::x86_64::syscalls::handlers::restart_syscall::syscall_restart_syscall(219),
        // 220 => arch::x86::x86_64::syscalls::handlers::semtimedop::syscall_semtimedop(220),
        // 221 => arch::x86::x86_64::syscalls::handlers::fadvise64::syscall_fadvise64(221),
        // 222 => arch::x86::x86_64::syscalls::handlers::timer_create::syscall_timer_create(222),
        // 223 => arch::x86::x86_64::syscalls::handlers::timer_settime::syscall_timer_settime(223),
        // 224 => arch::x86::x86_64::syscalls::handlers::timer_gettime::syscall_timer_gettime(224),
        // 225 => arch::x86::x86_64::syscalls::handlers::timer_getoverrun::syscall_timer_getoverrun(225),
        // 226 => arch::x86::x86_64::syscalls::handlers::timer_delete::syscall_timer_delete(226),
        // 227 => arch::x86::x86_64::syscalls::handlers::clock_settime::syscall_clock_settime(227),
        // 228 => arch::x86::x86_64::syscalls::handlers::clock_gettime::syscall_clock_gettime(228),
        // 229 => arch::x86::x86_64::syscalls::handlers::clock_getres::syscall_clock_getres(229),
        // 230 => arch::x86::x86_64::syscalls::handlers::clock_nanosleep::syscall_clock_nanosleep(230),
        // 231 => arch::x86::x86_64::syscalls::handlers::exit_group::syscall_exit_group(231),
        // 232 => arch::x86::x86_64::syscalls::handlers::epoll_wait::syscall_epoll_wait(232),
        // 233 => arch::x86::x86_64::syscalls::handlers::epoll_ctl::syscall_epoll_ctl(233),
        // 234 => arch::x86::x86_64::syscalls::handlers::tgkill::syscall_tgkill(234),
        // 235 => arch::x86::x86_64::syscalls::handlers::utimes::syscall_utimes(235),
        // 236 => arch::x86::x86_64::syscalls::handlers::vserver::syscall_vserver(236),
        // 237 => arch::x86::x86_64::syscalls::handlers::mbind::syscall_mbind(237),
        // 238 => arch::x86::x86_64::syscalls::handlers::set_mempolicy::syscall_set_mempolicy(238),
        // 239 => arch::x86::x86_64::syscalls::handlers::get_mempolicy::syscall_get_mempolicy(239),
        // 240 => arch::x86::x86_64::syscalls::handlers::mq_open::syscall_mq_open(240),
        // 241 => arch::x86::x86_64::syscalls::handlers::mq_unlink::syscall_mq_unlink(241),
        // 242 => arch::x86::x86_64::syscalls::handlers::mq_timedsend::syscall_mq_timedsend(242),
        // 243 => arch::x86::x86_64::syscalls::handlers::mq_timedreceive::syscall_mq_timedreceive(243),
        // 244 => arch::x86::x86_64::syscalls::handlers::mq_notify::syscall_mq_notify(244),
        // 245 => arch::x86::x86_64::syscalls::handlers::mq_getsetattr::syscall_mq_getsetattr(245),
        // 246 => arch::x86::x86_64::syscalls::handlers::kexec_load::syscall_kexec_load(246),
        // 247 => arch::x86::x86_64::syscalls::handlers::waitid::syscall_waitid(247),
        // 248 => arch::x86::x86_64::syscalls::handlers::add_key::syscall_add_key(248),
        // 249 => arch::x86::x86_64::syscalls::handlers::request_key::syscall_request_key(249),
        // 250 => arch::x86::x86_64::syscalls::handlers::keyctl::syscall_keyctl(250),
        // 251 => arch::x86::x86_64::syscalls::handlers::ioprio_set::syscall_ioprio_set(251),
        // 252 => arch::x86::x86_64::syscalls::handlers::ioprio_get::syscall_ioprio_get(252),
        // 253 => arch::x86::x86_64::syscalls::handlers::inotify_init::syscall_inotify_init(253),
        // 254 => arch::x86::x86_64::syscalls::handlers::inotify_add_watch::syscall_inotify_add_watch(254),
        // 255 => arch::x86::x86_64::syscalls::handlers::inotify_rm_watch::syscall_inotify_rm_watch(255),
        // 256 => arch::x86::x86_64::syscalls::handlers::migrate_pages::syscall_migrate_pages(256),
        // 257 => arch::x86::x86_64::syscalls::handlers::openat::syscall_openat(257),
        // 258 => arch::x86::x86_64::syscalls::handlers::mkdirat::syscall_mkdirat(258),
        // 259 => arch::x86::x86_64::syscalls::handlers::mknodat::syscall_mknodat(259),
        // 260 => arch::x86::x86_64::syscalls::handlers::fchownat::syscall_fchownat(260),
        // 261 => arch::x86::x86_64::syscalls::handlers::futimesat::syscall_futimesat(261),
        // 262 => arch::x86::x86_64::syscalls::handlers::newfstatat::syscall_newfstatat(262),
        // 263 => arch::x86::x86_64::syscalls::handlers::unlinkat::syscall_unlinkat(263),
        // 264 => arch::x86::x86_64::syscalls::handlers::renameat::syscall_renameat(264),
        // 265 => arch::x86::x86_64::syscalls::handlers::linkat::syscall_linkat(265),
        // 266 => arch::x86::x86_64::syscalls::handlers::symlinkat::syscall_symlinkat(266),
        // 267 => arch::x86::x86_64::syscalls::handlers::readlinkat::syscall_readlinkat(267),
        // 268 => arch::x86::x86_64::syscalls::handlers::fchmodat::syscall_fchmodat(268),
        // 269 => arch::x86::x86_64::syscalls::handlers::faccessat::syscall_faccessat(269),
        // 270 => arch::x86::x86_64::syscalls::handlers::pselect6::syscall_pselect6(270),
        // 271 => arch::x86::x86_64::syscalls::handlers::ppoll::syscall_ppoll(271),
        // 272 => arch::x86::x86_64::syscalls::handlers::unshare::syscall_unshare(272),
        // 273 => arch::x86::x86_64::syscalls::handlers::set_robust_list::syscall_set_robust_list(273),
        // 274 => arch::x86::x86_64::syscalls::handlers::get_robust_list::syscall_get_robust_list(274),
        // 275 => arch::x86::x86_64::syscalls::handlers::splice::syscall_splice(275),
        // 276 => arch::x86::x86_64::syscalls::handlers::tee::syscall_tee(276),
        // 277 => arch::x86::x86_64::syscalls::handlers::sync_file_range::syscall_sync_file_range(277),
        // 278 => arch::x86::x86_64::syscalls::handlers::vmsplice::syscall_vmsplice(278),
        // 279 => arch::x86::x86_64::syscalls::handlers::move_pages::syscall_move_pages(279),
        // 280 => arch::x86::x86_64::syscalls::handlers::utimensat::syscall_utimensat(280),
        // 281 => arch::x86::x86_64::syscalls::handlers::epoll_pwait::syscall_epoll_pwait(281),
        // 282 => arch::x86::x86_64::syscalls::handlers::signalfd::syscall_signalfd(282),
        // 283 => arch::x86::x86_64::syscalls::handlers::timerfd_create::syscall_timerfd_create(283),
        // 284 => arch::x86::x86_64::syscalls::handlers::eventfd::syscall_eventfd(284),
        // 285 => arch::x86::x86_64::syscalls::handlers::fallocate::syscall_fallocate(285),
        // 286 => arch::x86::x86_64::syscalls::handlers::timerfd_settime::syscall_timerfd_settime(286),
        // 287 => arch::x86::x86_64::syscalls::handlers::timerfd_gettime::syscall_timerfd_gettime(287),
        // 288 => arch::x86::x86_64::syscalls::handlers::accept4::syscall_accept4(288),
        // 289 => arch::x86::x86_64::syscalls::handlers::signalfd4::syscall_signalfd4(289),
        // 290 => arch::x86::x86_64::syscalls::handlers::eventfd2::syscall_eventfd2(290),
        // 291 => arch::x86::x86_64::syscalls::handlers::epoll_create1::syscall_epoll_create1(291),
        // 292 => arch::x86::x86_64::syscalls::handlers::dup3::syscall_dup3(292),
        // 293 => arch::x86::x86_64::syscalls::handlers::pipe2::syscall_pipe2(293),
        // 294 => arch::x86::x86_64::syscalls::handlers::inotify_init1::syscall_inotify_init1(294),
        // 295 => arch::x86::x86_64::syscalls::handlers::preadv::syscall_preadv(295),
        // 296 => arch::x86::x86_64::syscalls::handlers::pwritev::syscall_pwritev(296),
        // 297 => arch::x86::x86_64::syscalls::handlers::rt_tgsigqueueinfo::syscall_rt_tgsigqueueinfo(297),
        // 298 => arch::x86::x86_64::syscalls::handlers::perf_event_open::syscall_perf_event_open(298),
        // 299 => arch::x86::x86_64::syscalls::handlers::recvmmsg::syscall_recvmmsg(299),
        // 300 => arch::x86::x86_64::syscalls::handlers::fanotify_init::syscall_fanotify_init(300),
        // 301 => arch::x86::x86_64::syscalls::handlers::fanotify_mark::syscall_fanotify_mark(301),
        // 302 => arch::x86::x86_64::syscalls::handlers::prlimit64::syscall_prlimit64(302),
        // 303 => arch::x86::x86_64::syscalls::handlers::name_to_handle_at::syscall_name_to_handle_at(303),
        // 304 => arch::x86::x86_64::syscalls::handlers::open_by_handle_at::syscall_open_by_handle_at(304),
        // 305 => arch::x86::x86_64::syscalls::handlers::clock_adjtime::syscall_clock_adjtime(305),
        // 306 => arch::x86::x86_64::syscalls::handlers::syncfs::syscall_syncfs(306),
        // 307 => arch::x86::x86_64::syscalls::handlers::sendmmsg::syscall_sendmmsg(307),
        // 308 => arch::x86::x86_64::syscalls::handlers::setns::syscall_setns(308),
        // 309 => arch::x86::x86_64::syscalls::handlers::getcpu::syscall_getcpu(309),
        // 310 => arch::x86::x86_64::syscalls::handlers::process_vm_readv::syscall_process_vm_readv(310),
        // 311 => arch::x86::x86_64::syscalls::handlers::process_vm_writev::syscall_process_vm_writev(311),
        // 312 => arch::x86::x86_64::syscalls::handlers::kcmp::syscall_kcmp(312),
        // 313 => arch::x86::x86_64::syscalls::handlers::finit_module::syscall_finit_module(313),
        // 314 => arch::x86::x86_64::syscalls::handlers::sched_setattr::syscall_sched_setattr(314),
        // 315 => arch::x86::x86_64::syscalls::handlers::sched_getattr::syscall_sched_getattr(315),
        // 316 => arch::x86::x86_64::syscalls::handlers::renameat2::syscall_renameat2(316),
        // 317 => arch::x86::x86_64::syscalls::handlers::seccomp::syscall_seccomp(317),
        // 318 => arch::x86::x86_64::syscalls::handlers::getrandom::syscall_getrandom(318),
        // 319 => arch::x86::x86_64::syscalls::handlers::memfd_create::syscall_memfd_create(319),
        // 320 => arch::x86::x86_64::syscalls::handlers::kexec_file_load::syscall_kexec_file_load(320),
        // 321 => arch::x86::x86_64::syscalls::handlers::bpf::syscall_bpf(321),
        // 322 => arch::x86::x86_64::syscalls::handlers::execveat::syscall_execveat(322),
        _ => Err(anyhow::anyhow!(format!("Unhandled syscall requested: {}", idx)))
    }
}

pub const READ                            : usize = 0;
pub const WRITE                           : usize = 1;
pub const OPEN                            : usize = 2;
pub const CLOSE                           : usize = 3;
pub const STAT                            : usize = 4;
pub const FSTAT                           : usize = 5;
pub const LSTAT                           : usize = 6;
pub const POLL                            : usize = 7;
pub const LSEEK                           : usize = 8;
pub const MMAP                            : usize = 9;
pub const MPROTECT                        : usize = 10;
pub const MUNMAP                          : usize = 11;
pub const BRK                             : usize = 12;
pub const RT_SIGACTION                    : usize = 13;
pub const RT_SIGPROCMASK                  : usize = 14;
pub const RT_SIGRETURN                    : usize = 15;
pub const IOCTL                           : usize = 16;
pub const PREAD64                         : usize = 17;
pub const PWRITE64                        : usize = 18;
pub const READV                           : usize = 19;
pub const WRITEV                          : usize = 20;
pub const ACCESS                          : usize = 21;
pub const PIPE                            : usize = 22;
pub const SELECT                          : usize = 23;
pub const SCHED_YIELD                     : usize = 24;
pub const MREMAP                          : usize = 25;
pub const MSYNC                           : usize = 26;
pub const MINCORE                         : usize = 27;
pub const MADVISE                         : usize = 28;
pub const SHMGET                          : usize = 29;
pub const SHMAT                           : usize = 30;
pub const SHMCTL                          : usize = 31;
pub const DUP                             : usize = 32;
pub const DUP2                            : usize = 33;
pub const PAUSE                           : usize = 34;
pub const NANOSLEEP                       : usize = 35;
pub const GETITIMER                       : usize = 36;
pub const ALARM                           : usize = 37;
pub const SETITIMER                       : usize = 38;
pub const GETPID                          : usize = 39;
pub const SENDFILE                        : usize = 40;
pub const SOCKET                          : usize = 41;
pub const CONNECT                         : usize = 42;
pub const ACCEPT                          : usize = 43;
pub const SENDTO                          : usize = 44;
pub const RECVFROM                        : usize = 45;
pub const SENDMSG                         : usize = 46;
pub const RECVMSG                         : usize = 47;
pub const SHUTDOWN                        : usize = 48;
pub const BIND                            : usize = 49;
pub const LISTEN                          : usize = 50;
pub const GETSOCKNAME                     : usize = 51;
pub const GETPEERNAME                     : usize = 52;
pub const SOCKETPAIR                      : usize = 53;
pub const SETSOCKOPT                      : usize = 54;
pub const GETSOCKOPT                      : usize = 55;
pub const CLONE                           : usize = 56;
pub const FORK                            : usize = 57;
pub const VFORK                           : usize = 58;
pub const EXECVE                          : usize = 59;
pub const EXIT                            : usize = 60;
pub const WAIT4                           : usize = 61;
pub const KILL                            : usize = 62;
pub const UNAME                           : usize = 63;
pub const SEMGET                          : usize = 64;
pub const SEMOP                           : usize = 65;
pub const SEMCTL                          : usize = 66;
pub const SHMDT                           : usize = 67;
pub const MSGGET                          : usize = 68;
pub const MSGSND                          : usize = 69;
pub const MSGRCV                          : usize = 70;
pub const MSGCTL                          : usize = 71;
pub const FCNTL                           : usize = 72;
pub const FLOCK                           : usize = 73;
pub const FSYNC                           : usize = 74;
pub const FDATASYNC                       : usize = 75;
pub const TRUNCATE                        : usize = 76;
pub const FTRUNCATE                       : usize = 77;
pub const GETDENTS                        : usize = 78;
pub const GETCWD                          : usize = 79;
pub const CHDIR                           : usize = 80;
pub const FCHDIR                          : usize = 81;
pub const RENAME                          : usize = 82;
pub const MKDIR                           : usize = 83;
pub const RMDIR                           : usize = 84;
pub const CREAT                           : usize = 85;
pub const LINK                            : usize = 86;
pub const UNLINK                          : usize = 87;
pub const SYMLINK                         : usize = 88;
pub const READLINK                        : usize = 89;
pub const CHMOD                           : usize = 90;
pub const FCHMOD                          : usize = 91;
pub const CHOWN                           : usize = 92;
pub const FCHOWN                          : usize = 93;
pub const LCHOWN                          : usize = 94;
pub const UMASK                           : usize = 95;
pub const GETTIMEOFDAY                    : usize = 96;
pub const GETRLIMIT                       : usize = 97;
pub const GETRUSAGE                       : usize = 98;
pub const SYSINFO                         : usize = 99;
pub const TIMES                           : usize = 100;
pub const PTRACE                          : usize = 101;
pub const GETUID                          : usize = 102;
pub const SYSLOG                          : usize = 103;
pub const GETGID                          : usize = 104;
pub const SETUID                          : usize = 105;
pub const SETGID                          : usize = 106;
pub const GETEUID                         : usize = 107;
pub const GETEGID                         : usize = 108;
pub const SETPGID                         : usize = 109;
pub const GETPPID                         : usize = 110;
pub const GETPGRP                         : usize = 111;
pub const SETSID                          : usize = 112;
pub const SETREUID                        : usize = 113;
pub const SETREGID                        : usize = 114;
pub const GETGROUPS                       : usize = 115;
pub const SETGROUPS                       : usize = 116;
pub const SETRESUID                       : usize = 117;
pub const GETRESUID                       : usize = 118;
pub const SETRESGID                       : usize = 119;
pub const GETRESGID                       : usize = 120;
pub const GETPGID                         : usize = 121;
pub const SETFSUID                        : usize = 122;
pub const SETFSGID                        : usize = 123;
pub const GETSID                          : usize = 124;
pub const CAPGET                          : usize = 125;
pub const CAPSET                          : usize = 126;
pub const RT_SIGPENDING                   : usize = 127;
pub const RT_SIGTIMEDWAIT                 : usize = 128;
pub const RT_SIGQUEUEINFO                 : usize = 129;
pub const RT_SIGSUSPEND                   : usize = 130;
pub const SIGALTSTACK                     : usize = 131;
pub const UTIME                           : usize = 132;
pub const MKNOD                           : usize = 133;
pub const USELIB                          : usize = 134;
pub const PERSONALITY                     : usize = 135;
pub const USTAT                           : usize = 136;
pub const STATFS                          : usize = 137;
pub const FSTATFS                         : usize = 138;
pub const SYSFS                           : usize = 139;
pub const GETPRIORITY                     : usize = 140;
pub const SETPRIORITY                     : usize = 141;
pub const SCHED_SETPARAM                  : usize = 142;
pub const SCHED_GETPARAM                  : usize = 143;
pub const SCHED_SETSCHEDULER              : usize = 144;
pub const SCHED_GETSCHEDULER              : usize = 145;
pub const SCHED_GET_PRIORITY_MAX          : usize = 146;
pub const SCHED_GET_PRIORITY_MIN          : usize = 147;
pub const SCHED_RR_GET_INTERVAL           : usize = 148;
pub const MLOCK                           : usize = 149;
pub const MUNLOCK                         : usize = 150;
pub const MLOCKALL                        : usize = 151;
pub const MUNLOCKALL                      : usize = 152;
pub const VHANGUP                         : usize = 153;
pub const MODIFY_LDT                      : usize = 154;
pub const PIVOT_ROOT                      : usize = 155;
pub const _SYSCTL                         : usize = 156;
pub const PRCTL                           : usize = 157;
pub const ARCH_PRCTL                      : usize = 158;
pub const ADJTIMEX                        : usize = 159;
pub const SETRLIMIT                       : usize = 160;
pub const CHROOT                          : usize = 161;
pub const SYNC                            : usize = 162;
pub const ACCT                            : usize = 163;
pub const SETTIMEOFDAY                    : usize = 164;
pub const MOUNT                           : usize = 165;
pub const UMOUNT2                         : usize = 166;
pub const SWAPON                          : usize = 167;
pub const SWAPOFF                         : usize = 168;
pub const REBOOT                          : usize = 169;
pub const SETHOSTNAME                     : usize = 170;
pub const SETDOMAINNAME                   : usize = 171;
pub const IOPL                            : usize = 172;
pub const IOPERM                          : usize = 173;
pub const CREATE_MODULE                   : usize = 174;
pub const INIT_MODULE                     : usize = 175;
pub const DELETE_MODULE                   : usize = 176;
pub const GET_KERNEL_SYMS                 : usize = 177;
pub const QUERY_MODULE                    : usize = 178;
pub const QUOTACTL                        : usize = 179;
pub const NFSSERVCTL                      : usize = 180;
pub const GETPMSG                         : usize = 181;
pub const PUTPMSG                         : usize = 182;
pub const AFS_SYSCALL                     : usize = 183;
pub const TUXCALL                         : usize = 184;
pub const SECURITY                        : usize = 185;
pub const GETTID                          : usize = 186;
pub const READAHEAD                       : usize = 187;
pub const SETXATTR                        : usize = 188;
pub const LSETXATTR                       : usize = 189;
pub const FSETXATTR                       : usize = 190;
pub const GETXATTR                        : usize = 191;
pub const LGETXATTR                       : usize = 192;
pub const FGETXATTR                       : usize = 193;
pub const LISTXATTR                       : usize = 194;
pub const LLISTXATTR                      : usize = 195;
pub const FLISTXATTR                      : usize = 196;
pub const REMOVEXATTR                     : usize = 197;
pub const LREMOVEXATTR                    : usize = 198;
pub const FREMOVEXATTR                    : usize = 199;
pub const TKILL                           : usize = 200;
pub const TIME                            : usize = 201;
pub const FUTEX                           : usize = 202;
pub const SCHED_SETAFFINITY               : usize = 203;
pub const SCHED_GETAFFINITY               : usize = 204;
pub const SET_THREAD_AREA                 : usize = 205;
pub const IO_SETUP                        : usize = 206;
pub const IO_DESTROY                      : usize = 207;
pub const IO_GETEVENTS                    : usize = 208;
pub const IO_SUBMIT                       : usize = 209;
pub const IO_CANCEL                       : usize = 210;
pub const GET_THREAD_AREA                 : usize = 211;
pub const LOOKUP_DCOOKIE                  : usize = 212;
pub const EPOLL_CREATE                    : usize = 213;
pub const EPOLL_CTL_OLD                   : usize = 214;
pub const EPOLL_WAIT_OLD                  : usize = 215;
pub const REMAP_FILE_PAGES                : usize = 216;
pub const GETDENTS64                      : usize = 217;
pub const SET_TID_ADDRESS                 : usize = 218;
pub const RESTART_SYSCALL                 : usize = 219;
pub const SEMTIMEDOP                      : usize = 220;
pub const FADVISE64                       : usize = 221;
pub const TIMER_CREATE                    : usize = 222;
pub const TIMER_SETTIME                   : usize = 223;
pub const TIMER_GETTIME                   : usize = 224;
pub const TIMER_GETOVERRUN                : usize = 225;
pub const TIMER_DELETE                    : usize = 226;
pub const CLOCK_SETTIME                   : usize = 227;
pub const CLOCK_GETTIME                   : usize = 228;
pub const CLOCK_GETRES                    : usize = 229;
pub const CLOCK_NANOSLEEP                 : usize = 230;
pub const EXIT_GROUP                      : usize = 231;
pub const EPOLL_WAIT                      : usize = 232;
pub const EPOLL_CTL                       : usize = 233;
pub const TGKILL                          : usize = 234;
pub const UTIMES                          : usize = 235;
pub const VSERVER                         : usize = 236;
pub const MBIND                           : usize = 237;
pub const SET_MEMPOLICY                   : usize = 238;
pub const GET_MEMPOLICY                   : usize = 239;
pub const MQ_OPEN                         : usize = 240;
pub const MQ_UNLINK                       : usize = 241;
pub const MQ_TIMEDSEND                    : usize = 242;
pub const MQ_TIMEDRECEIVE                 : usize = 243;
pub const MQ_NOTIFY                       : usize = 244;
pub const MQ_GETSETATTR                   : usize = 245;
pub const KEXEC_LOAD                      : usize = 246;
pub const WAITID                          : usize = 247;
pub const ADD_KEY                         : usize = 248;
pub const REQUEST_KEY                     : usize = 249;
pub const KEYCTL                          : usize = 250;
pub const IOPRIO_SET                      : usize = 251;
pub const IOPRIO_GET                      : usize = 252;
pub const INOTIFY_INIT                    : usize = 253;
pub const INOTIFY_ADD_WATCH               : usize = 254;
pub const INOTIFY_RM_WATCH                : usize = 255;
pub const MIGRATE_PAGES                   : usize = 256;
pub const OPENAT                          : usize = 257;
pub const MKDIRAT                         : usize = 258;
pub const MKNODAT                         : usize = 259;
pub const FCHOWNAT                        : usize = 260;
pub const FUTIMESAT                       : usize = 261;
pub const NEWFSTATAT                      : usize = 262;
pub const UNLINKAT                        : usize = 263;
pub const RENAMEAT                        : usize = 264;
pub const LINKAT                          : usize = 265;
pub const SYMLINKAT                       : usize = 266;
pub const READLINKAT                      : usize = 267;
pub const FCHMODAT                        : usize = 268;
pub const FACCESSAT                       : usize = 269;
pub const PSELECT6                        : usize = 270;
pub const PPOLL                           : usize = 271;
pub const UNSHARE                         : usize = 272;
pub const SET_ROBUST_LIST                 : usize = 273;
pub const GET_ROBUST_LIST                 : usize = 274;
pub const SPLICE                          : usize = 275;
pub const TEE                             : usize = 276;
pub const SYNC_FILE_RANGE                 : usize = 277;
pub const VMSPLICE                        : usize = 278;
pub const MOVE_PAGES                      : usize = 279;
pub const UTIMENSAT                       : usize = 280;
pub const EPOLL_PWAIT                     : usize = 281;
pub const SIGNALFD                        : usize = 282;
pub const TIMERFD_CREATE                  : usize = 283;
pub const EVENTFD                         : usize = 284;
pub const FALLOCATE                       : usize = 285;
pub const TIMERFD_SETTIME                 : usize = 286;
pub const TIMERFD_GETTIME                 : usize = 287;
pub const ACCEPT4                         : usize = 288;
pub const SIGNALFD4                       : usize = 289;
pub const EVENTFD2                        : usize = 290;
pub const EPOLL_CREATE1                   : usize = 291;
pub const DUP3                            : usize = 292;
pub const PIPE2                           : usize = 293;
pub const INOTIFY_INIT1                   : usize = 294;
pub const PREADV                          : usize = 295;
pub const PWRITEV                         : usize = 296;
pub const RT_TGSIGQUEUEINFO               : usize = 297;
pub const PERF_EVENT_OPEN                 : usize = 298;
pub const RECVMMSG                        : usize = 299;
pub const FANOTIFY_INIT                   : usize = 300;
pub const FANOTIFY_MARK                   : usize = 301;
pub const PRLIMIT64                       : usize = 302;
pub const NAME_TO_HANDLE_AT               : usize = 303;
pub const OPEN_BY_HANDLE_AT               : usize = 304;
pub const CLOCK_ADJTIME                   : usize = 305;
pub const SYNCFS                          : usize = 306;
pub const SENDMMSG                        : usize = 307;
pub const SETNS                           : usize = 308;
pub const GETCPU                          : usize = 309;
pub const PROCESS_VM_READV                : usize = 310;
pub const PROCESS_VM_WRITEV               : usize = 311;
pub const KCMP                            : usize = 312;
pub const FINIT_MODULE                    : usize = 313;
pub const SCHED_SETATTR                   : usize = 314;
pub const SCHED_GETATTR                   : usize = 315;
pub const RENAMEAT2                       : usize = 316;
pub const SECCOMP                         : usize = 317;
pub const GETRANDOM                       : usize = 318;
pub const MEMFD_CREATE                    : usize = 319;
pub const KEXEC_FILE_LOAD                 : usize = 320;
pub const BPF                             : usize = 321;
pub const EXECVEAT                        : usize = 322;