[package]
name = "rvm"
version = "0.1.0"
authors = ["leo.karoubi <leokaroubi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.0.10"
goblin = "0.2.3"
libc = "0.2.71"
# burst = "0.0.1"